name: preprocessing
requirements:
  - torch==2.3.0
  - torchvision==0.18.0

input:
  - name: images
    type: torch.Tensor
    shape: [-1, 3, -1, -1]  
    format: ['batch size', 'channel', 'width', 'height']
    description: Images to be processed 
    required: true

output:
  - name: images
    type: torch.Tensor
    description: Processed images
    shape: [-1, 3, 416, 416]  
    format: ['batch size', 'channel', 'width', 'height']
    required: true
  
